version: '2'
services:
    laravel_library_db:
        image: mysql:5.7
        command: [
                '--default_authentication_plugin=mysql_native_password',
                '--character-set-server=utf8mb4',
                '--collation-server=utf8mb4_unicode_ci'
        ]
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - db-vol-library:/var/lib/mysql

    laravel_library_phpmyadmin:
        image: phpmyadmin
        environment:
            PMA_HOST: laravel_library_db
            PMA_PORT: 3306
        restart: always
        ports:
            - "8080:80"
volumes:
    db-vol-library:
